# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres-app
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - ./dataset:/docker-entrypoint-initdb.d

  app:
    image: quarkus/desafio.pp-jvm
    container_name: application
    environment:
      - DB_PASSWORD
      - DB_USER_NAME
      - DB_PORT=5432
      - DB_NAME
      - DB_URL=db
      - GENERATION=none
    depends_on:
      - db
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar123
    volumes:
      - sonarqube:/opt/sonarqube
    ports:
      - "9000:9000"

  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_CONNECTION_URI: jdbc:postgresql://db:5432/metabase
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data


volumes:
  sonarqube:
  postgresql:
  metabase-data:
