# Use postgres/example user/password credentials
version: '3.1'

services:

  db-app:
    image: postgres
    container_name: postgres-app
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  db-sonar:
    image: postgres:alpine
    container_name: postgres-sonar
    environment:
      POSTGRES_PASSWORD: sonar1234
      POSTGRES_USER: sonaruser
      POSTGRES_DB: sonar
    ports:
      - "5434:5432"
    volumes:
      - sonar_database:/var/lib/postgresql

  db-metabase:
    image: postgres:alpine
    container_name: postgres-metabase
    environment:
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
    ports:
      - "5435:5432"
    volumes:
      - metabase_database:/var/lib/postgresql


  app:
    image: quarkus/desafio.pp-jvm
    container_name: application
    environment:
      - DB_PASSWORD
      - DB_USER_NAME
      - DB_PORT
      - DB_NAME
      - DB_URL
      - GENERATION=none
    depends_on:
      - db-app
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db-sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonaruser
      SONAR_JDBC_PASSWORD: sonar1234
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_CONNECTION_URI: jdbc:postgresql://db-metabase:5432/metabase
    depends_on:
      - db-metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  metabase-data:
  sonar_database:
  metabase_database: