quarkus:
  hibernate-orm:
    database:
      generation:
        ~: none

  datasource:
    db-kind: postgresql
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
      max-size: 16

  rest-client:
    scope: jakarta.inject.Singleton
    authorization-api:
      url: ${AUTHORIZATION_API_URL}
    notification-api:
      url: ${NOTIFICATION_API_URL}