quarkus:
  hibernate-orm:
    database:
      generation:
        ~: drop-and-create

  datasource:
    db-kind: postgresql
    username: dev_user
    password: devuser123
    jdbc:
      url: jdbc:postgresql://localhost:${DB_PORT}/dev
      max-size: 16

  rest-client:
    scope: jakarta.inject.Singleton
    authorization-api:
      url: ${AUTHORIZATION_API_URL}
    notification-api:
      url: ${NOTIFICATION_API_URL}